lib/NotificationSettingsPage.dart, lib/models/CustomizedList.dart, lib/models/NotificationSetting.dart, lib/models/NotificationSettingList.dart, pubspec.yaml
+   整理flutter plugin
+   新增``CustomizedList``物件
+   把``List<NotificationSetting>``更新成物件``NotificationSettingList``
=> Update JSON serialization and deserialization

lib/helpers/boolBloc.dart, lib/homePage.dart, lib/models/editorChoiceService.dart, lib/widgets/carouselDisplayWidget.dart, lib/widgets/editorChoiceCarousel.dart, lib/widgets/tabContent.dart, pubspec.yaml
=> Add editor choice carousel and add loading more widget.

lib/homePage.dart, lib/models/newsMarqueeService.dart, lib/notificationSettingsPage.dart, lib/storyPage.dart, lib/widgets/editorChoiceCarousel.dart, lib/widgets/marqueeWidget.dart, lib/widgets/newsMarquee.dart, lib/widgets/newsMarqueeWidget.dart, lib/widgets/tabContent.dart
+   新增最新新聞跑馬燈
+   更新編輯精選
+   修改返回頂部bug
=> Add news scrolling text and fix some bug

lib/helpers/apiBaseHelper.dart, lib/helpers/apiResponse.dart, lib/helpers/appException.dart
+   新增api處理架構
Note:
reference to https://medium.com/flutter-community/handling-network-calls-like-a-pro-in-flutter-31bd30c86be1
=> Add api structure.

lib/blocs/tabContentBloc.dart, lib/models/editorChoiceService.dart, lib/widgets/editorChoiceCarousel.dart, lib/widgets/tabContent.dart
+   把編輯精選邏輯 加入 ``TabContentBloc``
=> Add editor choice to TabContentBloc.

lib/blocs/sectionBloc.dart, lib/models/sectionService.dart, lib/pages/homePage.dart
=> Add SectionBloc.

lib/pages/notificationSettingsPage.dart, lib/widgets/editorChoiceCarousel.dart, lib/widgets/marqueeWidget.dart, lib/widgets/newsMarqueeWidget.dart, lib/widgets/tabContent.dart
+   更改TabContent圖片大小
+   更新MarqueeWidget
+   更改跑馬燈字體大小
+   更改推播設定頁面
+   更新編輯精選UI(新增左右page切換按鈕)
=> Update some UI.

lib/models/category.dart, lib/models/categoryList.dart, lib/models/notificationSettingList.dart, lib/models/paragraph.dart, lib/models/paragrpahList.dart, lib/models/people.dart, lib/models/peopleList.dart, lib/models/recordList.dart, lib/models/sectionList.dart, lib/models/story.dart, lib/models/storyService.dart, lib/models/tag.dart, lib/models/tagList.dart, lib/pages/storyPage.dart, lib/widgets/editorChoiceCarousel.dart, lib/widgets/storyWidget.dart, lib/widgets/tabContent.dart
+   更新與story page相關的models
+   整合models的變數名稱
=> Update models related to story page.

lib/blocs/storyBloc.dart, lib/models/story.dart, lib/models/storyService.dart, lib/widgets/imageAndDescriptionSlideShowWidget.dart, lib/widgets/imageDescriptionWidget.dart, lib/widgets/storyWidget.dart
=> Add storyBloc.

lib/pages/notificationSettingsPage.dart
=> Fix NotificationSettingsPage.

lib/blocs/personalPageBloc.dart, lib/helpers/apiBaseHelper.dart, lib/models/category.dart, lib/models/categoryList.dart, lib/models/categoryService.dart, lib/models/personalSubscriptionService.dart, lib/pages/homePage.dart, lib/pages/notificationSettingsPage.dart, lib/pages/personalPage.dart, lib/widgets/listeningWidget.dart, pubspec.yaml
+ 新增個人訂閱頁面
+ 在http get的header中增加no-cache規則
=> Add personal page.

lib/blocs/listeningTabContentBloc.dart, lib/blocs/personalPageBloc.dart, lib/blocs/tabContentBloc.dart, lib/models/record.dart, lib/models/recordList.dart, lib/pages/personalPage.dart, lib/widgets/mMAudioPlayer.dart, lib/widgets/storyWidget.dart
+ 更新個人頁面
+ 解決會有重複slug出現在tab content的問題
+ 修正audio player的問題
=> Update personal page and fix some bugs.

lib/blocs/searchPageBloc.dart, lib/models/record.dart, lib/models/sectionList.dart, lib/pages/homePage.dart, lib/pages/searchPage.dart, lib/services/searchService.dart, lib/services/sectionService.dart, lib/widgets/searchWidget.dart
=> Add search page.

lib/blocs/listeningTabContentBloc.dart, lib/blocs/personalPageBloc.dart, lib/blocs/searchPageBloc.dart, lib/blocs/tabContentBloc.dart, lib/pages/personalPage.dart, lib/services/listeningTabContentService.dart, lib/services/personalSubscriptionService.dart, lib/services/recordService.dart, lib/widgets/listeningTabContent.dart, lib/widgets/tabContent.dart
+ 更改個人頁面、tab content 頁面與影音頁面的loading more邏輯
=> Change some loading more logic.

lib/helpers/dataConstants.dart, lib/widgets/listeningTabContent.dart, lib/widgets/mMAdBanner.dart, lib/widgets/tabContent.dart
+ 在listening tab content 中新增廣告
=> Add ad in ListeningTabContent.

lib/helpers/apiBaseHelper.dart, lib/helpers/cacheDurationCache.dart, lib/helpers/mMCacheManager.dart, lib/services/categoryService.dart, lib/services/editorChoiceService.dart, lib/services/listeningTabContentService.dart, lib/services/listeningWidgetService.dart, lib/services/recordService.dart, lib/services/sectionService.dart, lib/services/storyService.dart, pubspec.yaml
+ 在section新增快取
+ 在category新增快取
+ 在tab頁面(包含影音tab頁面)新增快取
+ 在story頁面(包含影音story頁面)新增快取
+ 在編輯精選頁面新增快取
=> Add cache in app.

android/app/src/main/AndroidManifest.xml, lib/helpers/appLinkHelper.dart, lib/pages/homePage.dart, pubspec.yaml
=> Add app link in android.

lib/models/content.dart, lib/widgets/embeddedCodeWidget.dart, lib/widgets/fbEmbeddedCodeWidget.dart
+ add twitter embedded code
+ add facebook embedded code
+ add instagram embedded code
=> Update embedded code widget.

android/app/build.gradle, lib/helpers/mMCacheManager.dart, lib/helpers/paragraphFormat.dart, lib/widgets/embeddedCodeWidget.dart, lib/widgets/errorStatelessWidget.dart, lib/widgets/fbEmbeddedCodeWidget.dart, lib/widgets/youtubeWidget.dart, pubspec.yaml
+ 更新 facebook iframe webview
+ 在 YoutubeWidget中新增AnimatedOpacity(讓載入更流暢)
+ 更改快取物件上限為100
+ 更新 ErrorStatelessWidget
+ 在embeddedcode中加入aspectRatio參數
+ 修復.dex文件超過64K(android only)
+ 升級一些套件
=> Update some UI and plugins.

lib/blocs/personalPageBloc.dart, lib/blocs/slugBloc.dart, lib/helpers/paragraphFormat.dart, lib/main.dart, lib/pages/storyPage.dart, lib/services/personalSubscriptionService.dart, lib/widgets/carouselDisplayWidget.dart, lib/widgets/editorChoiceCarousel.dart, lib/widgets/fbEmbeddedCodeWidget.dart, lib/widgets/imageAndDescriptionSlideShowWidget.dart, lib/widgets/listeningWidget.dart, lib/widgets/mMAdBanner.dart, lib/widgets/mMVideoPlayer.dart, lib/widgets/personalWidget.dart, lib/widgets/quoteByWidget.dart, lib/widgets/searchWidget.dart, lib/widgets/storyWidget.dart, lib/widgets/tabContent.dart
+ 更改story頁更多內容的文字大小
+ 更改video player播放前先載入影片正確比例
+ 更改banner ad顯示方式
+ 在story頁中新增分享功能
+ 更新搜尋頁面欄位比例
+ 更改hyper link顏色
+ 更改編輯精選比例
+ 更改quote by 文字大小顏色
+ 更改影音頁的title顏色為黑色
+ 更改personal page UI
+ 修正facebook embedded code的正規表達式的格式
=> Fix some bugs and update some UI.

lib/helpers/appUpgradeHelper.dart, lib/main.dart, lib/pages/homePage.dart, pubspec.yaml
=> Add in-app upgrade.

lib/blocs/listeningTabContentBloc.dart, lib/blocs/tabContentBloc.dart, lib/pages/homePage.dart, lib/widgets/listeningTabContent.dart, lib/widgets/listeningWidget.dart, lib/widgets/mMAdBanner.dart, lib/widgets/storyWidget.dart, lib/widgets/tabContent.dart
+ 使banner ad在tab listing中可以釋放
+ 把tab的listview轉成CustomScrollView
+ 在tab中新增navigateToStoryPage function
+ 把SectionAd參數移入tab bloc
+ 把HomePage內部的參數名稱改為private
=> Update some UI and improve performance.

.gitignore, android/app/build.gradle
=> Add android signing Configs.

lib/blocs/onBoardingBloc.dart, lib/main.dart, lib/models/onBoarding.dart, lib/models/onBoardingHint.dart, lib/pages/homePage.dart, lib/pages/notificationSettingsPage.dart, lib/widgets/holePainter.dart, lib/widgets/invertedClipper.dart, lib/widgets/personalWidget.dart
=> Add OnBoarding function.

lib/widgets/storyWidget.dart
=> Update story widget UI.

lib/helpers/appLinkHelper.dart, lib/helpers/firebaseMessangingHelper.dart, lib/helpers/routeGenerator.dart, lib/main.dart, lib/pages/homePage.dart, lib/widgets/carouselDisplayWidget.dart, lib/widgets/listeningTabContent.dart, lib/widgets/newsMarqueeWidget.dart, lib/widgets/personalWidget.dart, lib/widgets/searchWidget.dart, lib/widgets/tabContent.dart
=> Add dynamic route.

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, ios/Runner/Info.plist, ios/Runner/Runner.entitlements, lib/helpers/appLinkHelper.dart, lib/main.dart, lib/pages/homePage.dart, pubspec.yaml
=> Fix app link and set appsflyer.

lib/widgets/mMAdBanner.dart
=> Close tracking authorization in iOS Ad Banner.

lib/helpers/routeGenerator.dart, lib/main.dart, lib/mirrorApp.dart, test/widget_test.dart
=> Seperate main and mirrorApp.

ios/Runner/Runner.entitlements, lib/blocs/loginBLoc.dart, lib/helpers/loginResponse.dart, lib/helpers/routeGenerator.dart, lib/mirrorApp.dart, lib/models/firebaseLoginStatus.dart, lib/models/userData.dart, lib/pages/memberPage.dart, lib/services/emailSignInService.dart, lib/widgets/emailVerifyErrorWidget.dart, lib/widgets/fillInEmailLoginWidget.dart, lib/widgets/receiveEmailNotificationWidget.dart, lib/widgets/verifyEmailLoginWidget.dart, pubspec.yaml
+ 新增使用firebase email登入功能
+ 新增firebase 動態連結
+ 驗證登入UI
=> Add email login with firebase feature.

lib/widgets/listeningTabContent.dart
=> Fix ListeningTabContent navigate route.

assets/data/defaultNotificationList.json, lib/blocs/loginBLoc.dart, lib/models/notificationSettingList.dart, lib/pages/notificationSettingsPage.dart, lib/widgets/fbEmbeddedCodeWidget.dart, lib/widgets/mMAdBanner.dart, lib/widgets/memberWidget.dart
+ 在iOS上新增使用者數據廣告請求
+ 在會員介面刪除顯示使用者名稱
+ 更新facebook嵌入式code的regex
+ 修正推播json檔案，pisces id的title更正"牡羊座"為"雙魚座"
=> Fix some bugs.

lib/blocs/loginBLoc.dart, lib/helpers/apiBaseHelper.dart, lib/models/baseConfig.dart, lib/models/createMemberRes.dart, lib/models/graphqlBody.dart, lib/services/memberService.dart
=> Add calling createMember api after logging.

lib/blocs/loginBLoc.dart, lib/helpers/enumParser.dart, lib/models/userData.dart, lib/services/memberService.dart, lib/widgets/genderPicker.dart
+ 更新gender類別
+ 新增query member api
=> Add query member api.

lib/blocs/memberBloc.dart, lib/helpers/apiBaseHelper.dart, lib/helpers/dateTimeFormat.dart, lib/models/memberRes.dart, lib/services/memberService.dart, lib/widgets/birthdayPicker.dart, lib/widgets/editMemberContactInfo.dart, lib/widgets/editMemberProfile.dart
+ 新增更新會員資料api
+ 把datetime轉為Iso8601格式
+ 對api回傳的body bytes解碼為utf-8
=> Add update member data api.

lib/blocs/storyBloc.dart, lib/helpers/apiBaseHelper.dart, lib/models/baseConfig.dart, lib/models/category.dart, lib/models/categoryList.dart, lib/models/storyRes.dart, lib/services/memberService.dart, lib/services/storyService.dart, lib/widgets/storyWidget.dart
+ 更改api名稱graphqlApi為memberApi
+ 新增會員專屬頁面
=> Add is member only story page.

lib/helpers/apiBaseHelper.dart, lib/helpers/cacheDurationCache.dart, lib/helpers/mMCacheManager.dart, lib/services/categoryService.dart, lib/services/editorChoiceService.dart, lib/services/listeningTabContentService.dart, lib/services/listeningWidgetService.dart, lib/services/recordService.dart, lib/services/sectionService.dart, lib/services/storyService.dart
+ 更改function名稱getByCache為getByCacheAndAutoCache
+ 在ApiBaseHelper新增getByCache function
+ 把returnResponse function從private改成public
+ 新增非會員story page的快取
=> Add is not member story page cache.

lib/services/memberService.dart
+ 刪除create member api的nickname parameter
+ 將variables回傳null時轉成空字串
=> Fix MemberService api.

lib/blocs/checkTokenStateBloc.dart, lib/blocs/loginBLoc.dart, lib/blocs/magazineBloc.dart, lib/helpers/apiBaseHelper.dart, lib/helpers/cacheDurationCache.dart, lib/helpers/loginResponse.dart, lib/helpers/routeGenerator.dart, lib/models/baseConfig.dart, lib/models/magazine.dart, lib/models/magazineList.dart, lib/models/member.dart, lib/pages/magazineBrowser.dart, lib/pages/magazinePage.dart, lib/pages/memberPage.dart, lib/services/magazineService.dart, lib/services/memberService.dart, lib/widgets/downloadMagazineWidget.dart, lib/widgets/fillInEmailLoginWidget.dart, lib/widgets/magazineListWidget.dart, lib/widgets/storyWidget.dart, lib/widgets/verifyEmailLoginWidget.dart
+ 新增magazine and magazine list class
+ 新增magazine service
+ 新增magazine bloc
+ 新增magazine頁面UI
+ 新增magazine路由
+ 新增瀏覽magazine webview UI
+ 新增瀏覽magazine webview路由，如果是android就跳到網頁瀏覽(android webview pdf瀏覽上有些問題)，如果是iOS就在app中webview瀏覽
+ 在member service中新增驗證會員token state是否正確的api
+ 新增check token state bloc
+ 新增story頁中下載雜誌的UI
+ 更改email login驗證中的流程
+ 在會員頁面中新增登入完成後導覽的頁面目標
=> feat(magazine): add magazine feature

android/app/build.gradle, android/build.gradle, android/settings_aar.gradle, pubspec.yaml
+ add AndroidX migration file
+ 更新與firebase有關的套件
=> chore(package): upgrade some package

lib/pages/memberPage.dart, lib/widgets/editMemberProfile.dart
=> feat(member): change member UI

lib/blocs/loginBLoc.dart, lib/pages/storyPage.dart, lib/widgets/fadingEffectPainter.dart, lib/widgets/storyWidget.dart
+ 在文章中新增加入會員UI(當文章是會員限定與使用者未登入會員時)
+ 文章中最後一段顯示白色漸層(當文章是會員限定與使用者未登入會員時)
=> feat(story page): add locking story page feature

lib/blocs/listeningTabContentBloc.dart, lib/blocs/personalPageBloc.dart, lib/blocs/searchPageBloc.dart, lib/mirrorApp.dart
+ 修正dynamic links
+ 修正個人頁面、影音頁面、搜尋頁面loading more功能
=> fix: loading more and dynamic links

lib/blocs/magazine/bloc.dart, lib/blocs/magazine/events.dart, lib/blocs/magazine/states.dart, lib/models/magazineList.dart, lib/pages/magazine/magazineItemWidget.dart, lib/pages/magazine/magazinePage.dart, lib/pages/magazine/specialMagazineListWidget.dart, lib/pages/magazine/specialMagazineWidget.dart, lib/pages/magazine/weeklyMagazineListWidget.dart, lib/pages/magazine/weeklyMagazineWidget.dart, lib/services/magazineService.dart
+ 更改magazine widget 黨名為weekly magazine widget
+ 新增magazine item widget
+ 在magazine list類別中新增total參數
+ 在magazine services新增fetch next magazine list page by type api
+ 在magazine bloc新增fetch next magazine list page by type event
+ 新增special magazine UI
+ 在weekly magazine widget新增keep alive功能
=> feat(magazine): add special magazine list feature

lib/pages/emailLogin/emailLoginForm.dart, lib/pages/emailRegistered/emailRegisteredForm.dart, lib/pages/passwordReset/passwordResetForm.dart, lib/pages/passwordUpdate/oldPasswordConfirmForm.dart, lib/pages/passwordUpdate/passwordUpdateForm.dart, lib/pages/shared/passwordFormField.dart
+ 分離password form field為獨立一個widget
+ 修正password form field密碼顯示icon UI
=> feat(email password login): separate password form field to a shared widget

lib/widgets/mMAudioPlayer.dart, lib/widgets/mMVideoPlayer.dart
+ 更新音樂播放器主要顏色為橘色
+ 更新影片播放器自動抓取長寬比
=> feat(story page): update audio and video player UI

lib/blocs/story/bloc.dart, lib/blocs/story/events.dart, lib/blocs/story/states.dart, lib/pages/homePage.dart, lib/pages/termsOfService/mMTermsOfServicePage.dart, lib/pages/termsOfService/mMTermsOfServiceWidget.dart, lib/pages/termsOfService/termsOfServiceWidget.dart, lib/services/storyService.dart
+ 新增story bloc
+ 新增服務條款頁面
+ 新增顯示服務條款頁功能（當isAcceptTerms為null or false時顯示）
=> feat(terms of service): add showing terms of service page when user has not accepted it

lib/blocs/login/events.dart, lib/blocs/login/states.dart, lib/models/firebaseLoginStatus.dart, lib/pages/login/loginForm.dart, lib/services/loginService.dart
+ 新增registered by another method state
+ 新增通過其他方法註冊電子郵件時顯示登錄警告訊息UI
+ 新增當email登入時，有其他第三方已登入過的警告邏輯
+ 新增的第三方登入出現account-exists-with-different-credential訊息時，判斷是否使用其他方法登入過的警告邏輯
=> feat(login): display warning text if email is registered

lib/blocs/emailVerification/bloc.dart, lib/blocs/emailVerification/events.dart, lib/blocs/emailVerification/states.dart, lib/helpers/routeGenerator.dart, lib/models/baseConfig.dart, lib/pages/emailVerification/emailVerificationForm.dart, lib/pages/emailVerification/emailVerificationPage.dart, lib/pages/emailVerification/emailVerificationWidget.dart, lib/pages/passwordResetEmail/passwordResetEmailForm.dart, lib/pages/shared/sendingEmailButton.dart, lib/services/emailSignInService.dart
+ 修正發送密碼重設重新導向的url
+ 新增一個共用的sending email按鈕
+ 新增sending email verification api
+ 新增sending email verification bloc
+ 新增sending email verification UI
+ 新增email verification頁面route
+ 當登入者存在password登入方法時，無法改動寄送的email地址
=> feat(email verification): add sending email verification feature

lib/blocs/login/events.dart, lib/blocs/login/states.dart, lib/models/memberSubscriptionType.dart, lib/pages/login/loginWidget.dart, lib/pages/login/memberWidget.dart, lib/services/memberService.dart
+ 新增subscription type model
+ 新增判斷會員層級api
+ 在member widget新增subscription type參數
+ 更新member widget UI
=> feat(member subscription type): add subscription type in member widget

lib/blocs/tabContent/personal/cubit.dart, lib/blocs/tabContent/personal/state.dart, lib/pages/homePage.dart, lib/pages/tabContent/personal/memberSubscriptionTypeBlock.dart, lib/pages/tabContent/personal/personalTabContent.dart, lib/pages/tabContent/personal/personalWidget.dart
+ add personal tab content cubit
+ add member subscription type block in personal widget
+ rename personal widget to personal tab content
=> feat(personal tab content):  add member subscription type block in personal tab content

lib/blocs/paymentRecord/paymentRecordBloc.dart, lib/blocs/paymentRecord/paymentRecordEvent.dart, lib/blocs/paymentRecord/paymentRecordState.dart, lib/models/graphqlBody.dart, lib/models/paymentRecord.dart, lib/pages/login/memberWidget.dart, lib/pages/memberCenter/paymentRecord/memberPaymentRecordPage.dart, lib/services/paymentRecordService.dart
frequency目前是用subscription的，之後會改用newebpayPayment裡新開的frequency欄位
=> feat(Payment record page)

lib/mirrorApp.dart, lib/pages/emailVerification/emailVerificationForm.dart, lib/pages/emailVerification/emailVerificationSuccessPage.dart
Need change apiConstants finishEmailVerificationUrl
=> feat(emailVerifySuccessPage)

lib/helpers/appUpgradeHelper.dart, lib/mirrorApp.dart, lib/models/appVersion.dart, lib/models/baseConfig.dart, lib/pages/appUpdatePage.dart, lib/pages/homePage.dart, lib/services/appVersionSerivce.dart
+ 刪除舊版更新提示功能
+ 新增強制更新頁面
+ 新增判斷json顯示強制更新功能
=> feat(app version upgrade): add forced updating app version

lib/pages/emailVerification/emailVerificationSuccessPage.dart, lib/pages/login/memberWidget.dart, lib/pages/memberCenter/subscriptionSelect/hintToWebsitePage.dart, lib/pages/memberCenter/subscriptionSelect/subscriptionSelectPage.dart, lib/pages/tabContent/personal/memberSubscriptionTypeBlock.dart
1. Dynamic change subscriptionSelectPage appBar title
2. Navigate to a new hint page when in-app purchase not ready
=> feat(subscriptionSelect)

lib/blocs/memberCenter/editMemberContactInfo/bloc.dart, lib/blocs/memberCenter/editMemberContactInfo/events.dart, lib/blocs/memberCenter/editMemberContactInfo/states.dart, lib/blocs/memberCenter/editMemberProfile/bloc.dart, lib/blocs/memberCenter/editMemberProfile/events.dart, lib/blocs/memberCenter/editMemberProfile/states.dart, lib/helpers/routeGenerator.dart, lib/pages/login/memberWidget.dart, lib/pages/memberCenter/editMemberContactInfo/editMemberContactInfoPage.dart, lib/pages/memberCenter/editMemberContactInfo/editMemberContactInfoWidget.dart, lib/pages/memberCenter/editMemberProfile/editMemberProfilePage.dart, lib/pages/memberCenter/editMemberProfile/editMemberProfileWidget.dart
+ 刪除儲存成功和儲存失敗的state
+ 移除傳入bloc參數進入page頁面
+ 修正頁面轉換路由方式
=> refactor: refactor edit member profile and member contact info page

ios/Podfile.lock, lib/blocs/login/bloc.dart, lib/blocs/login/states.dart, lib/helpers/routeGenerator.dart, lib/models/memberSubscriptionType.dart, lib/pages/login/loginWidget.dart, lib/pages/login/memberWidget.dart, lib/pages/memberCenter/subscriptionSelect/newebpayChangePlanPage.dart, lib/pages/memberCenter/subscriptionSelect/subscriptionSelectWidget.dart, lib/pages/notificationSettingsPage.dart, lib/pages/shared/memberSubscriptionTypeTitleWidget.dart, lib/services/memberService.dart, pubspec.yaml
1. Add member type subscribe_group, hide button as marketing member
2. Add a page hint member that paid by newebpay go to website to change plan
=> feat: subscribe_group, block newebpay user change plan, add version and build number at bottom of setting page

ios/Podfile.lock, lib/configs/baseConfig.dart, lib/helpers/routeGenerator.dart, lib/models/magazine.dart, lib/models/magazineList.dart, lib/pages/magazine/magazineItemWidget.dart, lib/pages/magazine/magazineListLabel.dart, lib/pages/magazine/magazinePage.dart, lib/pages/magazine/specialMagazineListWidget.dart, lib/pages/magazine/weeklyMagazineListWidget.dart, lib/pages/magazineBrowser.dart, lib/pages/memberCenter/subscriptionSelect/subscriptionSelectWidget.dart, lib/pages/storyPage/news/shared/downloadMagazineWidget.dart, lib/services/magazineService.dart, pubspec.lock, pubspec.yaml
=> feat: change download magazine to online reading

lib/helpers/firebaseAnalyticsHelper.dart, lib/helpers/remoteConfigHelper.dart, lib/pages/homePage.dart, lib/widgets/popupRoute/easyPopup.dart, lib/widgets/popupRoute/sectionDropDownMenu.dart
+ 新增tab bar的A/B test([設計稿](https://www.figma.com/file/jkDRPpkaWQuqcZmZbBAfOD/Mirror-Media-App?node-id=2212%3A12720))
+ 新增tab bar第六個section之後的點擊紀錄firebase analytics(click event: `tab_bar_after_the_sixth_click`)
+ 將tab bar第六個section之後的點擊率設為A/B test追蹤勝出指標([參考連結](https://console.firebase.google.com/project/mirrormediaapptest/experiments/list))
=> feat(tab bar): add A/B test on home page tab bar

lib/pages/home/default/homeWidget.dart, lib/pages/home/premium/premiumHomePage.dart, lib/pages/home/premium/premiumHomeWidget.dart, lib/pages/login/memberWidget.dart, lib/pages/login/premiumMemberWidget.dart, lib/pages/memberCenter/subscriptionDetail/memberSubscriptionDetailPage.dart, lib/pages/shared/memberSubscriptionTypeTitleWidget.dart, lib/pages/tabContent/personal/default/memberSubscriptionTypeBlock.dart, lib/pages/tabContent/personal/premium/premiumMemberSubscriptionTypeBlock.dart, lib/widgets/popupRoute/sectionDropDownMenu.dart
+ 將`會員文章`文字敘述更新為 `Premium文章`
+ 更新Premium文章 header tab的顏色
+ 更新member subscription type widget的icon顏色
+ 更新header tab drop down menu(a/b test)的member label 顏色與文字敘述
=> feat(premium home page): updates some UI

lib/blocs/tabContent/bloc.dart, lib/blocs/tabContent/events.dart, lib/configs/baseConfig.dart, lib/helpers/apiBaseHelper.dart, lib/models/record.dart, lib/pages/tabContent/news/premiumTabContent.dart, lib/pages/tabContent/news/tabContent.dart, lib/services/recordService.dart
+ 將最新文章列表api改為json檔案
+ 最新文章列表json最多存在4個`post_external01.json - post_external04.json`
=> feat(latest tab content): changes latest tab content api

lib/blocs/externalStory/cubit.dart, lib/blocs/externalStory/states.dart, lib/configs/baseConfig.dart, lib/helpers/routeGenerator.dart, lib/models/externalStory.dart, lib/pages/storyPage/external/defaultBody.dart, lib/pages/storyPage/external/externalEmbeddedCodeWidget.dart, lib/pages/storyPage/external/externalStoryPage.dart, lib/pages/storyPage/external/externalStoryWidget.dart, lib/pages/tabContent/news/tabContent.dart, lib/services/externalStoryService.dart
+ 新增外部文章bloc
+ 新增外部文章UI
+ 新增外部文章route
+ 在tab content中判斷是否需要導航(navigate)至外部文章頁
=> feat(external story page): adds external story page in tab content

lib/helpers/routeGenerator.dart, lib/pages/storyPage/external/externalStoryPage.dart, lib/pages/storyPage/external/externalStoryWidget.dart, lib/pages/storyPage/external/premiumBody.dart, lib/pages/tabContent/news/premiumTabContent.dart
+ 在外部文章中新增premium mode
+ 新增外部文章route新增premium mode判斷
+ 在premium tab content中判斷是否需要導航(navigate)至premium mode的外部文章頁
=> feat(external story page): adds external story page premium mode

lib/blocs/login/bloc.dart, lib/blocs/memberCenter/subscriptionSelect/bloc.dart, lib/pages/memberCenter/subscriptionSelect/subscriptionSelectWidget.dart, lib/pages/storyPage/news/shared/joinMemberBlock.dart, lib/pages/tabContent/news/tabContent.dart
- show banner in 'premium文章' tab
- show subscriptionSelect even is not log in
- show login page if not login and tap buy button
=> chore: merge dev to prod

android/app/build.gradle, lib/pages/storyPage/news/storyWidget.dart, lib/widgets/infoBoxWidget.dart
- fix(storyPage): can't open link in infoBox
- build(android): upgrade ndk version to CI's version
=> fix(storyPage): can't open link in infoBox

pubspec.yaml
* chore: bump version to 4.5.4
* This is workflow testing.
=> chore: bump version to 4.5.4

lib/helpers/data_constants.dart, lib/helpers/date_time_format.dart, lib/pages/storyPage/external/default_body.dart, lib/pages/storyPage/external/premium_body.dart, lib/pages/storyPage/listening/listening_widget.dart, lib/pages/storyPage/news/premium_story_widget.dart, lib/pages/storyPage/news/story_widget.dart, pubspec.yaml
* Update datetime related format, fix timezone at GMT+8 and add "臺北時間" postfix.
* Bump version to 5.1.0
=> refactor: update datetime related format

lib/helpers/request_tracking_authorization.dart, lib/main_dev.dart, lib/main_prod.dart, pubspec.yaml
* fix ATT dialog not showing issue
=> fix: ATT dialog not showing issue

android/app/build.gradle, android/build.gradle, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/main_dev.dart, lib/main_prod.dart, lib/pages/home/default/home_page.dart, pubspec.lock, pubspec.yaml
* Add Firebase Crashlytics and related settings
* Add test button to HomePage (should be removed after verification)
* Bump version to 5.3.0
=> feat: add Firebase Crashlytics

lib/core/values/query.dart, lib/models/story.dart, lib/pages/search/search_widget.dart, lib/pages/storyPage/news/premium_story_widget.dart, lib/pages/topic_page/topic_page.dart
修改範圍：
* post: 相關文章、作者、section、category 按照手動排序排列
* invisible文章 不出現於列表頁
* debug 會員文章時，category 須抓 中文名稱而非英文（slug）
=> Fix(Story Page): post 相關文章、作者、section、category 按照手動排序排列

lib/core/values/query.dart, lib/models/content.dart, lib/models/paragraph.dart, lib/models/story.dart, lib/models/topic/topic_model.dart, lib/models/topic/topic_model.g.dart, lib/pages/topic_page/topic_page.dart, pubspec.yaml
新增功能:
Topic 首圖超連結
infobox 樣式顯示錯誤
video 改抓videoSrc
=> Feat(Topic Page): topic首圖超連結功能

lib/helpers/paragraph_format.dart, lib/models/content.dart, lib/models/paragraph.dart, lib/services/record_service.dart, lib/widgets/slideshow_widget/slideshow_controller.dart, lib/widgets/slideshow_widget/slideshow_widget.dart, lib/widgets/table_widget.dart, pubspec.yaml
修正 Slideshow-v2 , audio-v2 , table顯示上的錯誤
=> Feat(Story Page): Widget 修正

lib/initial_app.dart, pubspec.yaml
* 因應網站實作 custom email handler 後，重設密碼信與信箱驗證新中的 url 資訊調整，同步更新 app 處理 deeplink 資訊的邏輯
* 需要 https://github.com/mirror-media/apps-configs/pull/11 的調整內容
=> refactor: update deeplink path

lib/helpers/iap_subscription_helper.dart, lib/helpers/route_generator.dart, lib/pages/home/premium/premium_home_page.dart, lib/pages/login/member_widget/anonymous_block/anonymous_block_controller.dart, lib/pages/login/member_widget/member_widget.dart, lib/pages/login/member_widget/member_widget_controller.dart, lib/services/subscription_select_service.dart, pubspec.yaml
Reverts mirror-media/InstantCoffee#528
=> Revert "fix:修正IOS恢復訂閱"
